import type { CategoryType, FieldDefinition } from "@/types";

export const FIELD_DEFINITIONS: Partial<Record<CategoryType, FieldDefinition[]>> = {
  wedding_hall: [
    { key: "vendor", label: "업체명", type: "text" },
    { key: "manager", label: "담당자 / 연락처", type: "text" },
    { key: "address", label: "주소", type: "text" },
    { key: "event_date", label: "예식 날짜", type: "date" },
    { key: "event_time", label: "예식 시간", type: "text" },
    { key: "hall_name", label: "홀 이름", type: "text" },
    { key: "ceremony_type", label: "예식 형태", type: "select", options: ["일반", "채플", "야외", "하우스"] },
    { key: "rental_fee", label: "대관료", type: "number" },
    { key: "meal_price", label: "식대 단가 (1인)", type: "number" },
    { key: "guaranteed_guests", label: "보증인원", type: "number" },
    { key: "extra_guest_price", label: "추가인원 단가", type: "number" },
    { key: "flower_cost", label: "꽃장식 비용", type: "number" },
    { key: "pyebaek_cost", label: "폐백 음식 비용", type: "number" },
    { key: "parking_count", label: "주차 가능 대수", type: "number" },
    { key: "has_pyebaek_room", label: "폐백실 유무", type: "boolean" },
    { key: "has_bride_room", label: "신부대기실 유무", type: "boolean" },
    { key: "meal_type", label: "식사 메뉴", type: "select", options: ["뷔페", "한식", "양식", "중식"] },
    { key: "guest_waiting_area", label: "하객 대기 공간", type: "text" },
    { key: "ceremony_duration", label: "예식 시간 (분)", type: "number" },
    { key: "concurrent_ceremonies", label: "동시간대 예식 수", type: "number" },
    { key: "time_change_policy", label: "시간 변경 가능 여부", type: "text" },
    { key: "memo", label: "메모", type: "textarea" },
  ],
  sdm: [
    { key: "studio_vendor", label: "스튜디오 업체명", type: "text" },
    { key: "dress_vendor", label: "드레스 업체명", type: "text" },
    { key: "makeup_vendor", label: "메이크업 업체명", type: "text" },
    { key: "manager", label: "담당자 / 연락처", type: "text" },
    { key: "studio_cost", label: "스튜디오 촬영 비용", type: "number" },
    { key: "dress_cost", label: "드레스 대여 비용", type: "number" },
    { key: "makeup_cost", label: "메이크업 비용", type: "number" },
    { key: "package_total", label: "패키지 총 금액", type: "number" },
    { key: "shoot_concept", label: "촬영 컨셉 / 장소", type: "text" },
    { key: "shoot_date", label: "촬영 날짜", type: "date" },
    { key: "edited_photo_count", label: "보정본 수량", type: "number" },
    { key: "raw_photos_included", label: "원본 제공 여부", type: "boolean" },
    { key: "album_type", label: "앨범 종류 / 수량", type: "text" },
    { key: "fitting_date", label: "드레스 피팅 날짜", type: "date" },
    { key: "dress_type", label: "드레스 종류", type: "select", options: ["A라인", "머메이드", "볼가운", "엠파이어", "기타"] },
    { key: "rehearsal_makeup_date", label: "리허설 메이크업 날짜", type: "date" },
    { key: "ceremony_makeup_included", label: "본식 메이크업 포함 여부", type: "boolean" },
    { key: "extra_shoot_cost", label: "추가 촬영 비용 (시간당)", type: "number" },
    { key: "memo", label: "메모", type: "textarea" },
  ],

  home_goods: [
    { key: "appliance_list", label: "가전 목록", type: "textarea" },
    { key: "furniture_list", label: "가구 목록", type: "textarea" },
    { key: "living_goods_list", label: "생활용품 목록", type: "textarea" },
    { key: "item_cost", label: "품목별 금액", type: "number" },
    { key: "store", label: "구매처", type: "text" },
    { key: "purchase_status", label: "구매 상태", type: "select", options: ["예정", "주문", "배송중", "완료"] },
    { key: "delivery_date", label: "배송 예정일", type: "date" },
    { key: "cost_split", label: "신랑측/신부측 부담", type: "select", options: ["신랑측", "신부측", "공동"] },
    { key: "brand_model", label: "브랜드 / 모델명", type: "text" },
    { key: "memo", label: "메모", type: "textarea" },
  ],
  ceremony: [
    { key: "mc_name", label: "사회자 이름", type: "text" },
    { key: "mc_contact", label: "사회자 연락처", type: "text" },
    { key: "singer_name", label: "축가 가수명", type: "text" },
    { key: "singer_song", label: "축가 곡명", type: "text" },
    { key: "officiant_name", label: "주례 이름", type: "text" },
    { key: "officiant_org", label: "주례 소속", type: "text" },
    { key: "video_vendor", label: "영상 촬영 업체", type: "text" },
    { key: "snap_vendor", label: "스냅 촬영 업체", type: "text" },
    { key: "mc_cost", label: "사회자 비용", type: "number" },
    { key: "singer_cost", label: "축가 비용", type: "number" },
    { key: "video_cost", label: "영상 촬영 비용", type: "number" },
    { key: "snap_cost", label: "스냅 촬영 비용", type: "number" },
    { key: "ceremony_order", label: "식순", type: "textarea" },
    { key: "pyebaek_order", label: "폐백 순서", type: "textarea" },
    { key: "gift_collector", label: "축의금 수합 담당", type: "text" },
    { key: "reception_staff", label: "안내/접수 담당", type: "text" },
    { key: "flower_management", label: "화환 관리", type: "text" },
    { key: "memo", label: "메모", type: "textarea" },
  ],
  honeymoon: [
    { key: "destination", label: "여행지", type: "text" },
    { key: "travel_agency", label: "여행사 / 담당자", type: "text" },
    { key: "departure_date", label: "출발일", type: "date" },
    { key: "return_date", label: "귀국일", type: "date" },
    { key: "duration", label: "일정 (N박 N일)", type: "text" },
    { key: "package_cost", label: "패키지 총 비용", type: "number" },
    { key: "flight_cost", label: "항공권 비용", type: "number" },
    { key: "hotel_cost", label: "숙소 비용", type: "number" },
    { key: "insurance_cost", label: "여행자 보험", type: "number" },
    { key: "flight_info", label: "항공편 (편명/시간)", type: "text" },
    { key: "hotel_name", label: "숙소명 / 주소", type: "text" },
    { key: "hotel_type", label: "숙소 타입", type: "select", options: ["호텔", "리조트", "풀빌라", "에어비앤비", "기타"] },
    { key: "passport_expiry", label: "여권 유효기간 확인", type: "date" },
    { key: "visa_required", label: "비자 필요 여부", type: "boolean" },
    { key: "exchange_info", label: "환전 정보", type: "text" },
    { key: "activities", label: "액티비티 / 투어 예약", type: "textarea" },
    { key: "memo", label: "메모", type: "textarea" },
  ],

  jewelry: [
    { key: "vendor", label: "업체명 / 브랜드", type: "text" },
    { key: "manager", label: "담당자 / 연락처", type: "text" },
    { key: "ring_cost", label: "커플링 금액", type: "number" },
    { key: "watch_cost", label: "시계 금액", type: "number" },
    { key: "necklace_cost", label: "목걸이/귀걸이 금액", type: "number" },
    { key: "ring_material", label: "커플링 소재", type: "select", options: ["14K", "18K", "PT(백금)", "기타"] },
    { key: "ring_size", label: "커플링 사이즈", type: "text" },
    { key: "engraving", label: "각인 내용", type: "text" },
    { key: "pickup_date", label: "수령 예정일", type: "date" },
    { key: "warranty", label: "보증서 / AS 조건", type: "text" },
    { key: "memo", label: "메모", type: "textarea" },
  ],
  yedan: [
    { key: "yedan_type", label: "예단 형태", type: "select", options: ["현금", "현물", "혼합"] },
    { key: "groom_to_bride", label: "신랑측 → 신부측 금액", type: "number" },
    { key: "bride_to_groom", label: "신부측 → 신랑측 금액", type: "number" },
    { key: "hanbok_bride", label: "한복 (신부) 업체/금액", type: "text" },
    { key: "hanbok_groom", label: "한복 (신랑) 업체/금액", type: "text" },
    { key: "hanbok_mother_in_law", label: "한복 (시어머니) 업체/금액", type: "text" },
    { key: "hanbok_mother", label: "한복 (장모님) 업체/금액", type: "text" },
    { key: "bedding", label: "이불 (업체/수량/금액)", type: "text" },
    { key: "delivery_date", label: "예단 전달 날짜", type: "date" },
    { key: "ham_info", label: "함 (함진아비/날짜)", type: "text" },
    { key: "memo", label: "메모", type: "textarea" },
  ],
  invitation: [
    { key: "vendor", label: "업체명", type: "text" },
    { key: "manager", label: "담당자 / 연락처", type: "text" },
    { key: "unit_price", label: "단가 (장당)", type: "number" },
    { key: "total_cost", label: "총 금액", type: "number" },
    { key: "design_type", label: "디자인 종류", type: "select", options: ["종이", "모바일", "둘 다"] },
    { key: "quantity", label: "수량", type: "number" },
    { key: "design_confirm_date", label: "시안 확정일", type: "date" },
    { key: "print_complete_date", label: "인쇄 완료일", type: "date" },
    { key: "send_start_date", label: "발송 시작일", type: "date" },
    { key: "mobile_url", label: "모바일 청첩장 URL", type: "text" },
    { key: "message_content", label: "문구 내용", type: "textarea" },
    { key: "memo", label: "메모", type: "textarea" },
  ],
  newhome: [
    { key: "address", label: "주소", type: "text" },
    { key: "contract_type", label: "계약 형태", type: "select", options: ["전세", "월세", "매매"] },
    { key: "realtor", label: "부동산 / 담당자", type: "text" },
    { key: "deposit", label: "보증금 / 매매가", type: "number" },
    { key: "monthly_rent", label: "월세", type: "number" },
    { key: "interior_cost", label: "인테리어 비용", type: "number" },
    { key: "brokerage_fee", label: "중개수수료", type: "number" },
    { key: "area", label: "면적 (평수/㎡)", type: "text" },
    { key: "rooms", label: "방/화장실 수", type: "text" },
    { key: "move_in_date", label: "입주 예정일", type: "date" },
    { key: "contract_date", label: "계약일", type: "date" },
    { key: "interior_vendor", label: "인테리어 업체", type: "text" },
    { key: "interior_start_date", label: "인테리어 시작일", type: "date" },
    { key: "interior_end_date", label: "인테리어 완료일", type: "date" },
    { key: "memo", label: "메모", type: "textarea" },
  ],
};