import type { CategoryType, FieldDefinition } from "@/types";

export const FIELD_DEFINITIONS: Partial<Record<CategoryType, FieldDefinition[]>> = {
  wedding_hall: [
    { key: "vendor", label: "업체명", type: "text" },
    { key: "manager", label: "담당자 / 연락처", type: "text" },
    { key: "address", label: "주소", type: "text" },
    { key: "event_date", label: "예식 날짜", type: "date" },
    { key: "event_time", label: "예식 시간", type: "text" },
    { key: "hall_name", label: "홀 이름", type: "text" },
    { key: "ceremony_type", label: "예식 형태", type: "select", options: ["일반", "채플", "야외", "하우스"] },
    { key: "rental_fee", label: "대관료", type: "number" },
    { key: "meal_price", label: "식대 단가 (1인)", type: "number" },
    { key: "guaranteed_guests", label: "보증인원", type: "number" },
    { key: "memo", label: "메모", type: "textarea" },
  ],
  studio: [
    { key: "vendor", label: "업체명", type: "text" },
    { key: "manager", label: "담당자 / 연락처", type: "text" },
    { key: "cost", label: "촬영 비용", type: "number" },
    { key: "shoot_date", label: "촬영 날짜", type: "date" },
    { key: "shoot_concept", label: "촬영 컨셉 / 장소", type: "text" },
    { key: "edited_count", label: "보정본 수량", type: "number" },
    { key: "memo", label: "메모", type: "textarea" },
  ],
  dress: [
    { key: "vendor", label: "업체명", type: "text" },
    { key: "cost", label: "드레스 대여 비용", type: "number" },
    { key: "fitting_date", label: "피팅 날짜", type: "date" },
    { key: "dress_type", label: "드레스 종류", type: "select", options: ["A라인", "머메이드", "볼가운", "엠파이어", "기타"] },
    { key: "memo", label: "메모", type: "textarea" },
  ],
  hair_makeup: [
    { key: "vendor", label: "업체명", type: "text" },
    { key: "cost", label: "메이크업 비용", type: "number" },
    { key: "rehearsal_date", label: "리허설 날짜", type: "date" },
    { key: "ceremony_included", label: "본식 메이크업 포함", type: "boolean" },
    { key: "memo", label: "메모", type: "textarea" },
  ],
  invitation: [
    { key: "vendor", label: "업체명", type: "text" },
    { key: "design_type", label: "디자인 종류", type: "select", options: ["종이", "모바일", "둘 다"] },
    { key: "quantity", label: "수량", type: "number" },
    { key: "total_cost", label: "총 금액", type: "number" },
    { key: "send_date", label: "발송일", type: "date" },
    { key: "memo", label: "메모", type: "textarea" },
  ],
  video: [
    { key: "vendor", label: "업체명", type: "text" },
    { key: "cost", label: "촬영 비용", type: "number" },
    { key: "memo", label: "메모", type: "textarea" },
  ],
  mc: [
    { key: "name", label: "사회자 이름", type: "text" },
    { key: "contact", label: "연락처", type: "text" },
    { key: "cost", label: "비용", type: "number" },
    { key: "memo", label: "메모", type: "textarea" },
  ],
  singer: [
    { key: "name", label: "축가 가수명", type: "text" },
    { key: "song", label: "곡명", type: "text" },
    { key: "cost", label: "비용", type: "number" },
    { key: "memo", label: "메모", type: "textarea" },
  ],
  return_gift: [
    { key: "item", label: "답례품 종류", type: "text" },
    { key: "vendor", label: "업체명", type: "text" },
    { key: "quantity", label: "수량", type: "number" },
    { key: "cost", label: "총 비용", type: "number" },
    { key: "memo", label: "메모", type: "textarea" },
  ],
  meeting: [
    { key: "date", label: "상견례 날짜", type: "date" },
    { key: "location", label: "장소", type: "text" },
    { key: "restaurant", label: "식당명", type: "text" },
    { key: "cost", label: "비용", type: "number" },
    { key: "memo", label: "메모", type: "textarea" },
  ],
  wedding_ring: [
    { key: "vendor", label: "업체명 / 브랜드", type: "text" },
    { key: "cost", label: "금액", type: "number" },
    { key: "material", label: "소재", type: "select", options: ["14K", "18K", "PT(백금)", "기타"] },
    { key: "size", label: "사이즈", type: "text" },
    { key: "engraving", label: "각인 내용", type: "text" },
    { key: "memo", label: "메모", type: "textarea" },
  ],
  newhome: [
    { key: "address", label: "주소", type: "text" },
    { key: "contract_type", label: "계약 형태", type: "select", options: ["전세", "월세", "매매"] },
    { key: "deposit", label: "보증금 / 매매가", type: "number" },
    { key: "move_in_date", label: "입주 예정일", type: "date" },
    { key: "interior_cost", label: "인테리어 비용", type: "number" },
    { key: "memo", label: "메모", type: "textarea" },
  ],
  appliance: [
    { key: "item", label: "품목", type: "text" },
    { key: "brand", label: "브랜드 / 모델", type: "text" },
    { key: "cost", label: "금액", type: "number" },
    { key: "status", label: "구매 상태", type: "select", options: ["예정", "주문", "배송중", "완료"] },
    { key: "memo", label: "메모", type: "textarea" },
  ],
  furniture: [
    { key: "item", label: "품목", type: "text" },
    { key: "brand", label: "브랜드 / 모델", type: "text" },
    { key: "cost", label: "금액", type: "number" },
    { key: "status", label: "구매 상태", type: "select", options: ["예정", "주문", "배송중", "완료"] },
    { key: "memo", label: "메모", type: "textarea" },
  ],
  jewelry: [
    { key: "vendor", label: "업체명", type: "text" },
    { key: "cost", label: "금액", type: "number" },
    { key: "pickup_date", label: "수령 예정일", type: "date" },
    { key: "memo", label: "메모", type: "textarea" },
  ],
  yedan: [
    { key: "type", label: "예단 형태", type: "select", options: ["현금", "현물", "혼합"] },
    { key: "groom_to_bride", label: "신랑측 → 신부측", type: "number" },
    { key: "bride_to_groom", label: "신부측 → 신랑측", type: "number" },
    { key: "delivery_date", label: "전달 날짜", type: "date" },
    { key: "memo", label: "메모", type: "textarea" },
  ],
  honeymoon: [
    { key: "destination", label: "여행지", type: "text" },
    { key: "agency", label: "여행사 / 담당자", type: "text" },
    { key: "departure", label: "출발일", type: "date" },
    { key: "return", label: "귀국일", type: "date" },
    { key: "cost", label: "총 비용", type: "number" },
    { key: "hotel", label: "숙소", type: "text" },
    { key: "memo", label: "메모", type: "textarea" },
  ],
};
